### ISSUE TITLE
请问，有的医院没有在列表，如何添加呢？

### ISSUE THREAD

**Issue by creazy412** [lwm98/health160#10]
比如：深圳市龙岗区骨科医院 ，页面抓到了一些配置文件填写到main.py 文件了，但感觉没用

**Comment by creazy412** [comment]
想要的医院不在列表里

**Comment by lwm98** [comment]
注意噢，这个是健康160平台，这个医院上了平台的话就有，没上的话就没有。实在不好意思

**Comment by creazy412** [comment]
求证过了的【因为网页上就可以看得到】，已经上健康160平台了，
![](https://gitee.com/creazy1101/blog-image/raw/master/%E7%94%9F%E6%B4%BB/%E9%BE%99%E5%B2%97%E5%8C%BA%E9%AA%A8%E7%A7%91%E5%8C%BB%E9%99%A2.png)
