### ISSUE TITLE
抢票失败，正在重试，发生错误：'val'

### ISSUE THREAD

**Issue by mbskter** [lwm98/health160#13]
抢票失败，正在重试，发生错误：'val'
请问这个val是什么意思呢？
另外
我抢的也是东莞的九价 一般是什么时间段成功率高呢

**Comment by mbskter** [comment]
抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs'
抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs'

**Comment by S-HongJie** [comment]
我也想知道什么时候可以成功
捡漏失败了
昨天下午运行也是失败了

**Comment by lwm98** [comment]
> 抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs' 抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs'

这个是因为页面数据没有正确返回，可以打印一下当前行之前返回的页面数据。比对一下参数，能修改先尽量自己修改下，我这边上班 暂时抽不出时间来调这个，见谅

**Comment by lwm98** [comment]
> 抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs' 抢票失败，正在重试，发生错误：'NoneType' object has no attribute 'attrs'

简单来说就是：①要么160那边改请求参数了，没有响应回来的数据 ②要么就是你们选的这个医院/科目/没有返回数据

**Comment by lwm98** [comment]
可以的话 提供下日志（文件：atest.log）到我的邮箱 821256519@qq.com 我有空帮忙看看

**Comment by lwm98** [comment]
https://github.com/lwm98/health160/issues/6#issuecomment-975028164
