### ISSUE TITLE
显示抢票预约成功，可是没有短信通知

### ISSUE THREAD

**Issue by Maple-yhj** [lwm98/health160#14]
![image](https://user-images.githubusercontent.com/71971448/142757188-ddadb7da-616c-4475-b50e-528bdb86840e.png)

**Comment by lwm98** [comment]
可能请求参数官方那边又改了，这个得再去调试一下了

**Comment by lwm98** [comment]
刚刚去跑了一下其他科目的，确实是可以成功的。你这个不知道发生了什么其他的异常，判断条件过了，我这边再改下成功的判断条件。至于异常的话，得你那边自己调试了，没有号源和多的测试账号我这边复现不出来...
![微信图片_20211122104326](https://user-images.githubusercontent.com/48340898/142793464-0fc07c34-7c65-4713-b3f9-be9f37baab0b.jpg)

**Comment by Maple-yhj** [comment]
我这边也试过其他预约是可以的，但是不知道为什么九价第二针不可以。我看你的前言你好像也是帮女朋友在东莞抢九价，是也是在东华医院抢的吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lwm98 ***@***.***&gt;
发送时间: 2021年11月22日 10:47
收件人: lwm98/health160 ***@***.***&gt;
抄送: Maple-yhj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lwm98/health160] 显示抢票预约成功，可是没有短信通知 (Issue #14)





 
刚刚去跑了一下其他科目的，确实是可以成功的。你这个不知道发生了什么其他的异常，判断条件过了，我这边再改下成功的判断条件。至于异常的话，得你那边自己调试了，没有号源和多的测试账号我这边复现不出来...
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lwm98** [comment]
> 我这边也试过其他预约是可以的，但是不知道为什么九价第二针不可以。我看你的前言你好像也是帮女朋友在东莞抢九价，是也是在东华医院抢的吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lwm98 ***@***.***&gt; 发送时间: 2021年11月22日 10:47 收件人: lwm98/health160 ***@***.***&gt; 抄送: Maple-yhj ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [lwm98/health160] 显示抢票预约成功，可是没有短信通知 (Issue #14) 刚刚去跑了一下其他科目的，确实是可以成功的。你这个不知道发生了什么其他的异常，判断条件过了，我这边再改下成功的判断条件。至于异常的话，得你那边自己调试了，没有号源和多的测试账号我这边复现不出来... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的 现在还差一针就搞完了
