### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by jhl27** [lwm98/health160#19]
抢票的时候get_ticket 方法报这个，打印了一下响应，提示<bound method Response.json of <Response [404]>>，
这个地址https://www.91160.com/guahao/ystep1/uid-{}/depid-{}/schid-{}.html，

**Comment by lwm98** [comment]
https://github.com/lwm98/health160/issues/6#issuecomment-975028164

**Comment by lwm98** [comment]
> [#6 (comment)](https://github.com/lwm98/health160/issues/6#issuecomment-975028164)

问题原因在这里，这个我也没办法啦，因为是随机出现的，这个只能自己去调试了

**Comment by jhl27** [comment]
> > [#6 (comment)](https://github.com/lwm98/health160/issues/6#issuecomment-975028164)
> 
> 问题原因在这里，这个我也没办法啦，因为是随机出现的，这个只能自己去调试了

我是一直都出现，这个怎么调试呢，昨天准备抓包，随便挂了一个号，结果抓包软件没开启，白白浪费了一次

**Comment by lwm98** [comment]
只能抓包了，这个我也不知道为啥有的有报错，有的没有报错。

**Comment by lwm98** [comment]
也可以去官网挂号的时候看下，当页面到https://www.91160.com/guahao/ystep1/uid.....这个的时候，页面里面的dom元素（name: sch_data，name: mid）有没有值。 有可能是官网改成异步获取这个了，所以一直报这个错
