### ISSUE TITLE
大佬我想问一下是指定时间段可以实现吗？比如我想要18:30 - 19:00 / 19:00 - 19:30的号

### ISSUE THREAD

**Issue by LiuPure** [lwm98/health160#20]

**Comment by lwm98** [comment]
不能哦 现在只能大概的选择 上午  或者 下午。

**Comment by LiuPure** [comment]
好的噢谢谢

**Comment by LiuPure** [comment]
放号的时间点跑会报这个错，重启很多次报同样的错，但是过了几分钟再跑又可以了（啥也没改）, 这个报错能破吗大佬，感谢感谢
![截图_20212324092347](https://user-images.githubusercontent.com/43634342/147304508-654fbb17-f6d3-486f-92c0-a1489af19ebd.png)
