### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by Rong0119** [lwm98/health160#23]
请问是因为configs中除了账号和密码还要输入其他信息吗？ 
![image](https://user-images.githubusercontent.com/61425033/147270174-a3a13fea-0e26-4ea0-8ab7-af0dd6e6c863.png)

**Comment by Rong0119** [comment]
![image](https://user-images.githubusercontent.com/61425033/147270554-eeec23d6-f4b9-4d30-ad77-b1acd516ac25.png)
求大佬解答，谢谢！

**Comment by lwm98** [comment]
除了

**Comment by lwm98** [comment]
不过刚刚看到其他朋友运行这个项目，没有返回这个错误，所以需要你自行检查了
