### ISSUE TITLE
今天才发现你们有这玩意，我还花了3天时间写了一个

### ISSUE THREAD

**Issue by huangli58** [lwm98/health160#4]

**Comment by lwm98** [comment]
> https://www.91160.com/guahao/ysubmit.html 问一下，你们这个链接哪里取到的，我怎么看到的和你们的不一样？

在请求的最后一步提交预约那里有

**Comment by huangli58** [comment]
我这边找到的是H5端的，中间还有一步是获取提交的token，接口也不是这个。你这个是PC端的接口吗？

**Comment by lwm98** [comment]
> 我这边找到的是H5端的，中间还有一步是获取提交的token，接口也不是这个。你这个是PC端的接口吗？

是的
