### ISSUE TITLE
抢到号但是东华不让打

### ISSUE THREAD

**Issue by YIminta** [lwm98/health160#47]
据今天去打针的朋友描述，东华医院检测到那些号是软件抢到的，把账户全部拉黑了。具体检测规则是什么就不清楚了，所以朋友们还要继续用的慎重。详情去小红书上搜~

**Comment by YIminta** [comment]
emm，其实还有一个抢号软件叫【寻票】，还有官网估计用得人更多。。。全都遭殃
![908f57ec89e76a6c7684b2d5949a4f2](https://user-images.githubusercontent.com/50685567/169195376-5d371ea0-93be-4b9c-ba6a-d3a1df3cc584.jpg)

**Comment by lwm98** [comment]
黄牛渠道搞的号源就不要在这里说了。
