### ISSUE TITLE
假设性我账号有多个就诊人，有家人一起， 那么怎么选择就诊人呢

### ISSUE THREAD

**Issue by S-HongJie** [lwm98/health160#5]
请问作者一个问题
假设性我账号有多个就诊人，有家人一起， 那么怎么选择就诊人呢
是默认就诊人还是？

**Comment by lwm98** [comment]
是默认就诊人哦，不好意思，没有做选择就诊人的部分。
所以只能是，要抢哪个人，就登哪个人的账号，不要代抢。

**Comment by S-HongJie** [comment]
> 是默认就诊人哦，不好意思，没有做选择就诊人的部分。所以只能是，要抢哪个人，就登哪个人的账号，不要代抢。

好的 因为我账号有我爷爷信息 想问下如何
感谢作者
