### ISSUE TITLE
问一下作者，可以提供一下预约成功的城市吗

### ISSUE THREAD

**Issue by libra146** [lwm98/health160#8]
我看了一下天津和北京的科室，查询不到九价科室，不知道如何才能预约🤣

**Comment by S-HongJie** [comment]
> 我看了一下天津和北京的科室，查询不到九价科室，不知道如何才能预约全国太大了 各个城

**Comment by S-HongJie** [comment]
有些城市不是用健康160预约的 是另外的程序 建议查下当地用什么程序吧

**Comment by lwm98** [comment]
只有健康160这个平台的才行哦

**Comment by libra146** [comment]
@lwm98 @S-HongJie 好的，明白了，感谢！😀
